
#NVCC=nvcc --generate-line-info
NVCC=nvcc 

all:
	$(NVCC) -arch=sm_60 -O0 -c dot_product.cu
	$(NVCC) -arch=sm_60 -O0 -c main.cu
	$(NVCC) -o main dot_product.o main.o

clean:
	rm -rf *.o main __pycache__ *.ii .fpc_log.txt

